#!/bin/bash
#============================================================================
# Title:            setup_passwordless_sudo.sh
# Description:      Configure passwordless sudo for ollama-devops scripts
#                   Sets up restrictive sudoers rules and file permissions
# Author:           Keverall
# Date:             2026-04-30
# Version:          1.0.0
# Usage:            sudo ./scripts/initialisation/setup_passwordless_sudo.sh
# Requirements:     root/sudo access to install sudoers rules
#============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Ollama DevOps: Passwordless Sudo Setup${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}❌ Error: This script must be run as root${NC}"
    echo "   Run: sudo $0"
    exit 1
fi

# Determine target user
TARGET_USER="${1:-$SUDO_USER}"
if [[ -z "$TARGET_USER" ]]; then
    echo -e "${RED}❌ Error: Could not determine target user${NC}"
    echo "   Usage: sudo $0 [username]"
    exit 1
fi

echo -e "Configuring passwordless sudo for user: ${GREEN}$TARGET_USER${NC}"
echo ""

# Check if systemctl is available
if ! command -v systemctl &>/dev/null; then
    echo -e "${YELLOW}⚠️  systemctl not found. Skipping systemd sudoers configuration.${NC}"
    exit 0
fi

# Find absolute path to systemctl
SYSTEMCTL_BIN="$(command -v systemctl)"

# Build sudoers rules (restrictive - specific commands only)
SUDOERS_FILE="/etc/sudoers.d/ollama-devops"
SUDOERS_CONTENT="# ollama-devops: Passwordless sudo for Ollama service management
# Generated by setup_passwordless_sudo.sh on $(date)
# Security: Restrictive rules following Principle of Least Privilege
$TARGET_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_BIN start ollama
$TARGET_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_BIN stop ollama
$TARGET_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_BIN disable ollama
$TARGET_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_BIN enable ollama
$TARGET_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_BIN daemon-reload
$TARGET_USER ALL=(ALL) NOPASSWD: $SYSTEMCTL_BIN is-active --quiet ollama
"

# Validate syntax before installing
TEMP_FILE=$(mktemp)
echo "$SUDOERS_CONTENT" > "$TEMP_FILE"

echo -e "Validating sudoers syntax..."
if ! visudo -cf "$TEMP_FILE" &>/dev/null; then
    echo -e "${RED}❌ Error: Generated sudoers syntax is invalid${NC}"
    rm -f "$TEMP_FILE"
    exit 1
fi
echo -e "${GREEN}✅ Sudoers syntax valid${NC}"

# Install sudoers file
echo -e "Installing sudoers rules to ${SUDOERS_FILE}..."
cp "$TEMP_FILE" "$SUDOERS_FILE"
rm -f "$TEMP_FILE"

# Set restrictive permissions on sudoers file
chmod 440 "$SUDOERS_FILE"
chown root:root "$SUDOERS_FILE"
echo -e "${GREEN}✅ Sudoers file installed with permissions 440${NC}"

# Set restrictive permissions on devops scripts
echo -e "Setting restrictive permissions on devops scripts..."
for script in "$SCRIPT_DIR/sod.sh" "$SCRIPT_DIR/eod.sh"; do
    if [[ -f "$script" ]]; then
        chmod 750 "$script"
        echo -e "  ${GREEN}✅${NC} $(basename "$script") → 750"
    fi
done

# Verify setup works
echo ""
echo -e "Verifying passwordless sudo works..."
if su - "$TARGET_USER" -c "sudo -n $SYSTEMCTL_BIN is-active --quiet ollama" 2>/dev/null; then
    echo -e "${GREEN}✅ Passwordless sudo verified successfully${NC}"
elif su - "$TARGET_USER" -c "sudo -n $SYSTEMCTL_BIN daemon-reload" 2>/dev/null; then
    echo -e "${GREEN}✅ Passwordless sudo verified successfully${NC}"
else
    echo -e "${YELLOW}⚠️  Verification inconclusive (ollama service may not be running)${NC}"
    echo -e "   Test manually: sudo -n $SYSTEMCTL_BIN status ollama"
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Setup Complete${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Allowed commands for $TARGET_USER:"
echo "  • systemctl start ollama"
echo "  • systemctl stop ollama"
echo "  • systemctl disable ollama"
echo "  • systemctl enable ollama"
echo "  • systemctl daemon-reload"
echo "  • systemctl is-active --quiet ollama"
echo ""
echo "To revoke: sudo rm $SUDOERS_FILE"
echo ""
